/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import models.DBConnection;


/**
 *
 * @author Thimathi
 */
public class viewAllRecords extends javax.swing.JFrame {

    /**
     * Creates new form viewAllRecords
     */
    
      
    
    DefaultTableModel model;
    
    public viewAllRecords() {
        initComponents();
        setbookDetailsToTable();
    }

       public void setbookDetailsToTable(){
    
    
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","root");
        java.sql.PreparedStatement pst =  con.prepareStatement("SELECT * FROM  issuebookdetails");
        ResultSet rs = pst.executeQuery();
        
        
        if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "No Records");
        }
        else{
            while(rs.next()){
            String ID = rs.getString("id");
            String bookName = rs.getString("bookName");
            String studentName = rs.getString("studentName");
            String issueDate = rs.getString("issueDate");
            String dueDate = rs.getString("dueDate");
            String status = rs.getString("status");
            
            Object [] obj = {ID,bookName,studentName,issueDate,dueDate,status};
            model = (DefaultTableModel) tbl_viewAllRecord.getModel();
            model.addRow(obj);
        }
        }
           
        }
    catch(Exception ex){
         ex.getMessage();
    }
            }
        //to fetch the record using data fields
    public void search() {
    Date ufromDate = fromDate.getDatoFecha();
    Date utoDate = toDate.getDatoFecha();

    long l1 = ufromDate.getTime();
    long l2 = utoDate.getTime();

    java.sql.Date sqlFromDate = new java.sql.Date(l1);
    java.sql.Date sqlToDate = new java.sql.Date(l2);

    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("SELECT * FROM issuebookdetails WHERE issueDate BETWEEN ? AND ?");
        pst.setDate(1, sqlFromDate);
        pst.setDate(2, sqlToDate);

        ResultSet rs = pst.executeQuery();

        // Clear existing rows from the table
        DefaultTableModel model = (DefaultTableModel) tbl_viewAllRecord.getModel();
        model.setRowCount(0);
        
        if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "No Records");
        }
        else{
        while (rs.next()) {
            String ID = rs.getString("id");
            String bookName = rs.getString("bookName");
            String studentName = rs.getString("studentName");
            String issueDate = rs.getString("issueDate");
            String dueDate = rs.getString("dueDate");
            String status = rs.getString("status");

            Object[] obj = {ID, bookName, studentName, issueDate, dueDate, status};
            model.addRow(obj);
        }
        }
    } catch (Exception ex) {
        ex.printStackTrace(); // Print the stack trace for debugging
        // Handle the exception appropriately, e.g., display an error message
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_viewAllRecord.getModel();
        model.setRowCount(0);
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fromDate = new rojeru_san.componentes.RSDateChooser();
        toDate = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_viewAllRecord = new rojerusan.RSTableMetro();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(590, 130, 320, 5);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("View All Records");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 20, 290, 110);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Due Date :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(930, 170, 130, 30);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Issue Date :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(210, 170, 130, 30);

        fromDate.setColorBackground(new java.awt.Color(153, 153, 0));
        fromDate.setColorButtonHover(new java.awt.Color(204, 0, 0));
        fromDate.setColorDiaActual(new java.awt.Color(204, 0, 0));
        fromDate.setColorForeground(new java.awt.Color(153, 153, 0));
        jPanel1.add(fromDate);
        fromDate.setBounds(350, 170, 240, 40);

        toDate.setColorBackground(new java.awt.Color(153, 153, 0));
        toDate.setColorButtonHover(new java.awt.Color(204, 0, 0));
        toDate.setColorDiaActual(new java.awt.Color(204, 0, 0));
        toDate.setColorForeground(new java.awt.Color(153, 153, 0));
        jPanel1.add(toDate);
        toDate.setBounds(1070, 170, 240, 40);

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(204, 0, 0));
        rSMaterialButtonCircle1.setActionCommand("SEARCH");
        rSMaterialButtonCircle1.setLabel("SEARCH");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1);
        rSMaterialButtonCircle1.setBounds(630, 210, 220, 70);

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel1.add(jPanel5);
        jPanel5.setBounds(1450, 0, 30, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_viewAllRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_viewAllRecord.setColorBackgoundHead(new java.awt.Color(153, 153, 0));
        tbl_viewAllRecord.setColorBordeFilas(new java.awt.Color(153, 153, 0));
        tbl_viewAllRecord.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_viewAllRecord.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_viewAllRecord.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tbl_viewAllRecord.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_viewAllRecord.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_viewAllRecord.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_viewAllRecord.setRowHeight(40);
        tbl_viewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_viewAllRecordMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_viewAllRecord);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 70, 1401, 440));

        rSMaterialButtonRectangle1.setText("GET ALL RECORDS");
        rSMaterialButtonRectangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle1MouseClicked(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1480, 580));

        setSize(new java.awt.Dimension(1481, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_viewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_viewAllRecordMouseClicked

        
    }//GEN-LAST:event_tbl_viewAllRecordMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

       adminDashboard obj = new adminDashboard();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        if(fromDate.getDatoFecha() != null && toDate.getDatoFecha() != null){
            search();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please Select A Date");
        }
        
        
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void rSMaterialButtonRectangle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1MouseClicked
    clearTable(); 
    setbookDetailsToTable();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser fromDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSTableMetro tbl_viewAllRecord;
    private rojeru_san.componentes.RSDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
